resources:
  - https://raw.githubusercontent.com/ooraini/k8s-random-password/v0.1.0/job.yaml

namePrefix: redis-

patchesJson6902:
  - target:
      kind: Job
      version: v1
      name: random-password
    patch: |-
      - op: replace
        path: /spec/template/metadata/annotations/secretKey
        value: admin-password
